# vib_build.yml
- name: Build VIB file
  hosts: localhost
  become: true
  gather_facts: true
  become_method: sudo
  serial: 1
  vars_files:
    - vars/all.yml
  tasks:
    - name: Creating file list
      find:
        paths: "{{vib_payload_dir}}"
        recurse: yes
      register: filelist

    - name: Creating tar file
      archive:
        path: "{{vib_payload_dir}}"
        dest: "{{vib_payload_dir}}oem.tar"
        format: tar

    - name: Generating sha1 checksum of new tarfile
      stat:
        path: "{{vib_payload_dir}}oem.tar"
        get_checksum: yes
        checksum_algorithm: sha1
      register: vib_sha1

    - name: Compressing tarfile
      archive:
        path: "{{vib_payload_dir}}oem.tar"
        dest: "{{vib_payload_dir}}{{vib_payload}}"
        format: gz

    - name: Generating sha256 checksum of new gzip file
      stat:
        path: "{{vib_payload_dir}}{{vib_payload}}"
        get_checksum: yes
        checksum_algorithm: sha256
      register: vib_sha256

    - name: Print filelist
      debug:
        msg: "File List: {{filelist}}"
      when: >
        vib_debug is defined and
        vib_debug

    - name: Print filelist
      debug:
        msg: "File List: {{filelist['files'][0]['path']}}"
      when: >
        vib_debug is defined and
        vib_debug

    - name: Print vib_sha1
      debug:
        msg: "{{vib_sha1}}"
      when: >
        vib_debug is defined and
        vib_debug

    - name: Print vib_sha256
      debug:
        msg: "{{vib_sha256}}"
      when: >
        vib_debug is defined and
        vib_debug

    - name: Print vib_sha256 checksum
      debug:
        msg: "{{vib_sha256['stat']['checksum']}}"
      when: >
        vib_debug is defined and
        vib_debug

    - name: Print Datetime
      debug:
        msg: "Date: {{ansible_date_time.iso8601_micro}}"
      when: >
        vib_debug is defined and
        vib_debug

    - name: Build descriptor.xml
      template:
        src: templates/descriptor.xml.j2
        dest: "{{vib_payload_dir}}descriptor.xml"

    - name: Create empty sig file
      file:
        path: "{{vib_payload_dir}}sig.pkcs7"
        state: touch

    - name: Build VIB archive
      shell:
        cmd: "ar qDv {{vib_dist_dir}}{{vib_payload}}_$(date +%Y-%m-%d_%H%M).vib {{vib_payload_dir}}descriptor.xml {{vib_payload_dir}}sig.pkcs7 {{vib_payload_dir}}{{vib_payload}}"